http:
  routers:
    granite-embedding-router:
      rule: "Host(`granite-embedding.internal.thinkheads.ai`)"
      service: "granite-embedding-service"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

    granite-3b-router:
      rule: "Host(`granite-3b.internal.thinkheads.ai`)"
      service: "granite-3b-service"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

    ollama-router:
      rule: "Host(`ollama.internal.thinkheads.ai`)"
      service: "ollama-service"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

    llamacpp-router:
      rule: "Host(`llamacpp.internal.thinkheads.ai`)"
      service: "llamacpp-service"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

    portainer-router:
      rule: "Host(`portainer.internal.thinkheads.ai`)"
      service: "portainer-service"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
  
  services:
    granite-embedding-service:
      loadBalancer:
        servers:
          - url: "http://granite-embedding.internal.thinkheads.ai:8000"

    granite-3b-service:
      loadBalancer:
        servers:
          - url: "http://granite-3b.internal.thinkheads.ai:8000"

    ollama-service:
      loadBalancer:
        servers:
          - url: "http://ollama.internal.thinkheads.ai:11434"

    llamacpp-service:
      loadBalancer:
        servers:
          - url: "http://llamacpp.internal.thinkheads.ai:8081"

    portainer-service:
      loadBalancer:
        servers:
          - url: "https://portainer.internal.thinkheads.ai:9443"